--DELETE TABLES
drop table hm_reserva;
drop table hm_habitacion;
drop table hm_usuario;
drop table hm_persona;
drop table hm_tipohabitacion;
drop table hm_hotel;
commit;

--CREATE TABLES
CREATE TABLE HM_HABITACION
  (
    habi_id   NUMBER NOT NULL ,
    habi_codi CHAR (5) NOT NULL ,
    tiph_id   NUMBER NOT NULL
  ) ;
ALTER TABLE HM_HABITACION ADD CONSTRAINT HM_HABITACION_PK PRIMARY KEY ( habi_id ) ;
CREATE TABLE HM_HOTEL
  (
    hote_id   NUMBER NOT NULL ,
    hote_nomb VARCHAR2 (50) NOT NULL ,
    hote_desc VARCHAR2 (100) ,
    hote_cate VARCHAR2 (50) ,
    hote_dire VARCHAR2 (50) ,
    hote_pobl VARCHAR2 (50) ,
    hote_prov VARCHAR2 (50) ,
    hote_codp VARCHAR2 (6) ,
    hote_telf VARCHAR2 (20)
  ) ;
ALTER TABLE HM_HOTEL ADD CONSTRAINT HM_HOTEL_PK PRIMARY KEY ( hote_id ) ;
CREATE TABLE HM_PERSONA
  (
    --pers_id   NUMBER GENERATED AS IDENTITY,
	pers_id   NUMBER,
    pers_nomb VARCHAR2 (50) NOT NULL ,
    pers_apel VARCHAR2 (50) NOT NULL ,
    pers_dire VARCHAR2 (50) ,
    pers_pobl VARCHAR2 (50) ,
    pers_prov VARCHAR2 (50) ,
    pers_codp VARCHAR2 (6) ,
    pers_telf VARCHAR2 (20)
  ) ;
ALTER TABLE HM_PERSONA ADD CONSTRAINT HM_CLIENTE_PK PRIMARY KEY ( pers_id ) ;
CREATE TABLE HM_RESERVA
  (
    rese_id   NUMBER NOT NULL ,
    rese_fini DATE NOT NULL ,
    rese_ffin DATE NOT NULL ,
    rese_tota NUMBER (10,2) NOT NULL ,
    clie_id   NUMBER NOT NULL ,
    empl_id   NUMBER ,
    habi_id   NUMBER NOT NULL ,
    rese_esta CHAR (1) NOT NULL
  ) ;
ALTER TABLE HM_RESERVA ADD CONSTRAINT HM_RESERVA_PK PRIMARY KEY ( rese_id ) ;
CREATE TABLE HM_TIPOHABITACION
  (
    tiph_id   NUMBER NOT NULL ,
    tiph_nomb VARCHAR2 (50) NOT NULL ,
    tiph_desc VARCHAR2 (50) NOT NULL ,
    tiph_cpac NUMBER ,
    tiph_prec NUMBER (10,2) NOT NULL ,
    hote_id   NUMBER NOT NULL
  ) ;
ALTER TABLE HM_TIPOHABITACION ADD CONSTRAINT HM_TIPO_HABITACION_PK PRIMARY KEY ( tiph_id ) ;
CREATE TABLE HM_USUARIO
  (
    user_id   NUMBER NOT NULL ,
    user_user VARCHAR2 (20) NOT NULL ,
    user_pass VARCHAR2 (20) NOT NULL ,
    user_emai VARCHAR2 (30) NOT NULL ,
    user_freg DATE NOT NULL ,
    user_facc DATE ,
    user_esta CHAR (1) NOT NULL ,
    user_rol  CHAR (1) NOT NULL ,
    pers_id   NUMBER NOT NULL
  ) ;
ALTER TABLE HM_USUARIO ADD CONSTRAINT HM_USUARIO_PK PRIMARY KEY ( user_id ) ;
--ALTER TABLE HM_USUARIO ADD CONSTRAINT HM_USUARIO__UN_EMAI UNIQUE ( user_emai ) ;
ALTER TABLE HM_USUARIO ADD CONSTRAINT HM_USUARIO__UN_PERS_ROL UNIQUE ( pers_id , user_rol ) ;
--ALTER TABLE HM_USUARIO ADD CONSTRAINT HM_USUARIO__UN_USER UNIQUE ( user_user ) ;
ALTER TABLE HM_HABITACION ADD CONSTRAINT HM_HABITACION_HM_TIPO_FK FOREIGN KEY ( tiph_id ) REFERENCES HM_TIPOHABITACION ( tiph_id ) ;
ALTER TABLE HM_RESERVA ADD CONSTRAINT HM_RESERVA_HM_HABITACION_FK FOREIGN KEY ( habi_id ) REFERENCES HM_HABITACION ( habi_id ) ;
ALTER TABLE HM_RESERVA ADD CONSTRAINT HM_RESERVA_HM_USUARIO_CLIE FOREIGN KEY ( clie_id ) REFERENCES HM_USUARIO ( user_id ) ;
ALTER TABLE HM_RESERVA ADD CONSTRAINT HM_RESERVA_HM_USUARIO_EMPL FOREIGN KEY ( empl_id ) REFERENCES HM_USUARIO ( user_id ) ;
ALTER TABLE HM_TIPOHABITACION ADD CONSTRAINT HM_TIPOHABITACION_HM_HOTEL_FK FOREIGN KEY ( hote_id ) REFERENCES HM_HOTEL ( hote_id ) ;
ALTER TABLE HM_USUARIO ADD CONSTRAINT HM_USUARIO_HM_PERSONA_FK FOREIGN KEY ( pers_id ) REFERENCES HM_PERSONA ( pers_id ) ;
commit;


